spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: application-service
          uri: http://localhost:8081
          predicates:
            - Path=/application/**
          filters:
            - RewritePath=/application/(?<segment>.*), /$\{segment}
            - TokenRelay=
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8888/auth/realms/viaconto/protocol/openid-connect/token
            authorization-uri: http://localhost:8888/auth/realms/viaconto/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8888/auth/realms/viaconto/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          keycloak-with-viaconto-client-scope:
            provider: keycloak
            client-id: viaconto-client
            client-secret: 31c4ff73-2b74-45ca-9f7e-e3a9cc7d9d7a
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

server.port: 8080

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: DEBUG